# welcome to numpy

In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.0.0


In [3]:
arr = np.array([1, 2, 3, 4])

In [4]:
print(arr)

[1 2 3 4]


In [5]:
arr

array([1, 2, 3, 4])

In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

In [9]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr.ndim

1

In [11]:
print(arr.ndim)

1


In [12]:
arr1.ndim

2

In [13]:
arr[0]

np.int64(1)

In [14]:
print(arr[0])

1


In [15]:
arr1[1, 1]

np.int64(5)

In [16]:
print(arr.dtype)

int64


In [17]:
print(arr1.dtype)

int64


In [21]:
arr3 = np.array([1, 2, 3, 4], dtype = 'S')

In [22]:
arr3

array([b'1', b'2', b'3', b'4'], dtype='|S1')

In [23]:
arr4 = np.array([1.1, 2.2, 3.3, 4.4])

In [26]:
newarr = arr4.astype('bool')

In [27]:
newarr

array([ True,  True,  True,  True])

In [28]:
arr5 = np.array([1, 2, 3, 4, 5])

In [29]:
x = arr5.copy()

In [30]:
arr[0] = 42

In [31]:
arr

array([42,  2,  3,  4])

In [32]:
x

array([1, 2, 3, 4, 5])

In [33]:
x[0] = 50

In [34]:
x

array([50,  2,  3,  4,  5])

In [35]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])


In [36]:
narr = arr.reshape(4, 3)

In [37]:
narr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [38]:
narr = arr.reshape(2, 6)

In [39]:
narr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [41]:
narr = arr.reshape(2, 3, 2)

In [42]:
narr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [43]:
narr = arr.reshape(3, 2, 2)

In [44]:
narr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [45]:
print(narr.base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [47]:
print(arr.reshape(2, 6).base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [48]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [49]:
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [52]:
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [53]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [54]:
for i in arr:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12


In [56]:
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [59]:
arr = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]])

In [61]:
arr.ndim

4

In [62]:
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8


In [68]:
zeros = np.zeros((2, 2, 3))

In [69]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [70]:
rng = np.arange(15)

In [71]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [72]:
lspace = np.linspace(1, 50, 10)

In [73]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [ ]:
emp 