# Practice numpy

In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.0.0


In [3]:
arr1 = np.arange(0, 10)

In [4]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr2 = np.ones((3, 3), dtype = bool)

In [6]:
arr2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [7]:
arr3 = arr1.copy()
arr3[arr3 % 2 == 1] = -1

In [8]:
arr3

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [9]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr = np.arange(10)

In [11]:
arr.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [13]:
a, b

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]))

In [14]:
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [15]:
np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [16]:
a = np.array([1,2,3])

In [19]:
c = np.repeat(a, 3)
d = np.tile(a, 3)

In [20]:
c

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [21]:
d

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [22]:
np.hstack([c, d])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [23]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [24]:
a == b

array([False,  True, False,  True, False,  True, False,  True, False,
       False])

In [26]:
index = np.where(a == b)
np.unique(a.take(index))

array([2, 4])

In [28]:
np.intersect1d(a, b)

array([2, 4])

In [37]:
new = np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
nand = np.random.uniform(5, 10, size=(5, 3))

In [43]:
nand

array([[9.45775764, 7.10375327, 9.07998684],
       [7.58554247, 5.69173308, 8.2443762 ],
       [5.55354874, 9.37201545, 5.64827313],
       [7.32025023, 6.09068173, 8.82388662],
       [5.22873135, 5.45016543, 5.54500127]])

In [44]:
np.random.random((5, 3))

array([[0.77745221, 0.87211172, 0.17310694],
       [0.92884133, 0.3316825 , 0.80702001],
       [0.93793322, 0.28606036, 0.01014823],
       [0.81882511, 0.31376569, 0.86776275],
       [0.15186249, 0.86489583, 0.618244  ]])

In [45]:
np.random.random([5, 3])

array([[0.85585429, 0.60637855, 0.88241561],
       [0.1489185 , 0.48986632, 0.82062988],
       [0.37710657, 0.43740739, 0.87823748],
       [0.4798276 , 0.28348855, 0.6905819 ],
       [0.69137822, 0.0742858 , 0.59743097]])

In [ ]:
np.set_